# Generated by Django 5.1.6 on 2025-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='duration',
            field=models.CharField(choices=[('Several hours', 'Несколько часов'), ('1 day', '1 день'), ('Several days', 'Несколько дней')], default='1 day', max_length=50),
        ),
        migrations.AddField(
            model_name='excursion',
            name='group_type',
            field=models.CharField(choices=[('Group', 'Групповые'), ('Individual', 'Индивидуальные'), ('Family', 'Семейные')], default='Group', max_length=50),
        ),
        migrations.AddField(
            model_name='excursion',
            name='language',
            field=models.CharField(choices=[('Kazakh', 'Казахский'), ('Russian', 'Русский'), ('English', 'Английский')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='location',
            field=models.CharField(choices=[('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='tour_type',
            field=models.CharField(choices=[('Full Day Tour', 'Full Day Tour')], default='Full Day Tour', max_length=100),
        ),
    ]
