# Generated by Django 5.1.6 on 2025-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0003_excursion_duration_excursion_group_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='tour_type',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
