# Generated by Django 5.1.6 on 2025-03-07 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0004_remove_excursion_tour_type_alter_excursion_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='duration',
            field=models.CharField(choices=[('Несколько часов', 'Несколько часов'), ('1 день', '1 день'), ('Несколько дней', 'Несколько дней')], default='1 day', max_length=50),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='group_type',
            field=models.CharField(choices=[('Групповые', 'Групповые'), ('Индивидуальные', 'Индивидуальные'), ('Семейные', 'Семейные')], default='Group', max_length=50),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='language',
            field=models.CharField(choices=[('Казахский', 'Казахский'), ('Русский', 'Русский'), ('Английский', 'Английский')], default='English', max_length=50),
        ),
    ]
