# Generated by Django 5.1.6 on 2025-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0005_excursion_end_time_excursion_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursion',
            name='guide_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
