# Generated by Django 5.1.6 on 2025-03-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0006_excursion_description_excursion_guide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='food_included',
            field=models.BooleanField(default=False, verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='group_first_aid',
            field=models.BooleanField(default=False, verbose_name='Групповая аптечка'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='guide_services',
            field=models.BooleanField(default=False, verbose_name='Услуги гида/водителя'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='included_lunch',
            field=models.BooleanField(default=False, verbose_name='Включенный обед'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='transfer_service',
            field=models.BooleanField(default=False, verbose_name='Трансфер на протяжении всего пути'),
        ),
    ]
