# Generated by Django 5.1.6 on 2025-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0007_excursion_food_included_excursion_group_first_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Даты проведения'),
        ),
    ]
