# Generated by Django 5.1.6 on 2025-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0008_excursion_dates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedexcursion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookedexcursion',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookedexcursion',
            unique_together={('user', 'excursion', 'booking_date')},
        ),
    ]
