# Generated by Django 5.1.6 on 2025-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0009_alter_bookedexcursion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedexcursion',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
