# Generated by Django 5.1.6 on 2025-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0010_bookedexcursion_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedexcursion',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
