# Generated by Django 5.1.6 on 2025-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0011_bookedexcursion_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='encrypted_card_number',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
