# Generated by Django 5.1.6 on 2025-03-21 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0012_customuser_cardholder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_card_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expiry_date',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_card_number', models.BinaryField(blank=True, null=True)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
