# Generated by Django 5.1.6 on 2025-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0013_remove_customuser_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedexcursion',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
