# Generated by Django 5.1.6 on 2025-03-24 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0015_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_excursions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
