# Generated by Django 5.0.2 on 2025-04-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0018_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='Программа экскурсии'),
        ),
    ]
