# Generated by Django 5.0.2 on 2025-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0019_excursion_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
