# Generated by Django 5.0.2 on 2025-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0020_excursion_end_date_excursion_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='start_date',
        ),
        migrations.AddField(
            model_name='excursion',
            name='days_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество дней'),
        ),
    ]
