# Generated by Django 5.0.2 on 2025-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0021_remove_excursion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место встречи'),
        ),
    ]
