# Generated by Django 5.0.2 on 2025-04-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0022_excursion_meeting_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='meeting_point',
        ),
    ]
