# Generated by Django 5.0.2 on 2025-04-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0023_remove_excursion_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место встречи'),
        ),
    ]
