# Generated by Django 5.0.2 on 2025-04-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0024_excursion_meeting_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='meeting_point',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='days_count',
            field=models.IntegerField(blank=True, help_text='Количество дней для многодневных экскурсий', null=True),
        ),
    ]
