# Generated by Django 5.0.2 on 2025-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0025_remove_excursion_meeting_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='days_count',
        ),
        migrations.AddField(
            model_name='excursion',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество дней'),
        ),
    ]
