# Generated by Django 5.1.6 on 2025-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0026_remove_excursion_days_count_excursion_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
