# Generated by Django 5.1.6 on 2025-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0027_alter_excursion_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='meeting_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес места встречи'),
        ),
    ]
