# Generated by Django 5.1.6 on 2025-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0028_excursion_meeting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='end_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место окончания экскурсии'),
        ),
    ]
