# Generated by Django 5.1.6 on 2025-05-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0029_excursion_end_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='guide_avatar',
            field=models.BinaryField(blank=True, null=True, verbose_name='Аватар гида'),
        ),
    ]
