# Generated by Django 5.2.1 on 2025-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0032_simplereview_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplereview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
