# Generated by Django 5.2.1 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0033_simplereview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplereview',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
