# Generated by Django 5.2.1 on 2025-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0034_simplereview_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.BinaryField(blank=True, null=True, verbose_name='Аватар пользователя'),
        ),
    ]
