# Generated by Django 5.2.1 on 2025-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0035_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Аватар пользователя'),
        ),
    ]
