# Generated by Django 5.2.1 on 2025-05-21 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0036_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='language',
        ),
        migrations.AddField(
            model_name='excursion',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Казахский', 'Казахский'), ('Русский', 'Русский'), ('Английский', 'Английский')], max_length=50), blank=True, default=list, size=None, verbose_name='Языки проведения'),
        ),
    ]
