# Generated by Django 5.2.1 on 2025-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0038_excursionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcursionImage',
        ),
    ]
