# Generated by Django 5.2.1 on 2025-05-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0039_delete_excursionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='image_name',
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(verbose_name='Изображение')),
                ('image_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excursionapp.excursion')),
            ],
            options={
                'verbose_name': 'Изображение экскурсии',
                'verbose_name_plural': 'Изображения экскурсий',
                'ordering': ['order'],
            },
        ),
    ]
