# Generated by Django 5.2.1 on 2025-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursionapp', '0040_remove_excursion_image_remove_excursion_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ExcursionImage',
        ),
    ]
